# Site settings
title: VLA-edge
logo: /assets/images/manumite-logo.webp
description: 

# Use GitHub's minimal theme
theme: jekyll-theme-minimal

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default